# Generated by Django 2.2.5 on 2019-10-02 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bottombox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rca',
            name='completed_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rca',
            name='date_completed',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='date_uploaded',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
