# Generated by Django 2.2.4 on 2019-09-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottombox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rca',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
