# Generated by Django 2.2.5 on 2019-11-22 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bottombox', '0002_auto_20191021_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb_driver_code2',
            name='dsat_Code1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bb_Driver_Code2s', to='bottombox.DSAT_Code1'),
        ),
        migrations.AlterField(
            model_name='bb_driver_code3',
            name='bb_Driver_Code2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bb_Driver_Code3s', to='bottombox.BB_Driver_Code2'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='follow_up_comments',
            field=models.CharField(blank=True, max_length=10000, verbose_name='Follow up Comments'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q1',
            field=models.CharField(blank=True, max_length=10000, verbose_name='Q1. We understand that your request has been resolved, is this correct?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q2',
            field=models.CharField(blank=True, max_length=10000, verbose_name='Q2. How much effort did you personally have to put forth to handle your request? Where 1 = A great deal and 5 = Very little'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q2a',
            field=models.CharField(blank=True, max_length=10000, verbose_name='Q2a. Which aspect of the experience disappointed you?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q3a',
            field=models.CharField(blank=True, max_length=10000, verbose_name='Q3a. Which aspect of the experience disappointed you?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q4',
            field=models.CharField(blank=True, max_length=10000, verbose_name="Q4. How was your overall experience in relation to this issue or request? Where 1 = Didn't meet any of my needs and 5 = Met all of my needs"),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q5',
            field=models.CharField(blank=True, max_length=10000, verbose_name='Q5. Would you like to add any further comments about your recent experience?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q6',
            field=models.CharField(blank=True, max_length=10000, verbose_name='Q6. Lastly, would you like us to contact you again regarding this ticket?'),
        ),
    ]
