# Generated by Django 2.2.4 on 2019-09-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottombox', '0002_rca_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rca',
            name='completed',
        ),
        migrations.AddField(
            model_name='survey',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
