# Generated by Django 2.2.5 on 2019-10-08 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bottombox', '0002_auto_20191003_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='follow_up_commnets',
            new_name='follow_up_comments',
        ),
    ]
