# Generated by Django 2.2.5 on 2019-10-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottombox', '0003_auto_20191008_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='rca',
            name='agent',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
