# Generated by Django 2.2.5 on 2019-10-20 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bottombox', '0004_rca_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb_driver_code2',
            name='bb_Driver_Code3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bb_Driver_Code3', to='bottombox.BB_Driver_Code3'),
        ),
        migrations.AddField(
            model_name='dsat_code1',
            name='bb_Driver_Code2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bb_Driver_Code2', to='bottombox.BB_Driver_Code2'),
        ),
    ]
