# Generated by Django 2.2.5 on 2019-10-20 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bottombox', '0006_auto_20191020_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb_driver_code2',
            name='dsat_Code1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bb_Driver_Code2s', to='bottombox.DSAT_Code1'),
        ),
        migrations.AddField(
            model_name='bb_driver_code3',
            name='bb_Driver_Code2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bb_Driver_Code3s', to='bottombox.BB_Driver_Code2'),
        ),
    ]
