export const CHECK_BUTTON_COLOR = "CHECK_BUTTON_COLOR";
export const GET_ALL_DATA_CCMS = "GET_ALL_DATA_CCMS";

export const GET_SURVEYS = "GET_SURVEYS";
export const ADD_SURVEY = "ADD_SURVEY";
export const DELETE_SURVEY = "DELETE_SURVEY";
export const MODAL_TOGGLE = "MODAL_TOGGLE";
export const GET_SURVEY = "GET_SURVEY";
export const REMOVE_SURVEY = "REMOVE_SURVEY";
export const GET_AGENT = "GET_AGENT";
export const GET_AGENTS = "GET_AGENTS";
export const GET_SKILLS = "GET_SKILLS";
export const ADD_FAILED_SURVEY = "ADD_FAILED_SURVEY";

export const GET_BOTTOMBOX_SURVEY_VIEW = "GET_BOTTOMBOX_SURVEY_VIEW";
export const GET_TOPBOX_SURVEY_VIEW = "GET_TOPBOX_SURVEY_VIEW";
export const GET_COMPLETED_SURVEY_VIEW = "GET_COMPLETED_SURVEY_VIEW";
export const GET_ALL_SURVEY_VIEW = "GET_ALL_SURVEY_VIEW";

export const GET_TEAMS = "GET_TEAMS";
export const ADD_RCA = "ADD_RCA";
export const UPDATE_BOTTOMBOX_NOT_COMPLETED = "UPDATE_BOTTOMBOX_NOT_COMPLETED";
export const FETCHING_CCMS = "FETCHING_CCMS";
export const STOP_FETCHING_CCMS = "STOP_FETCHING_CCMS";
export const FETCHING = "FETCHING";
export const STOP_FETCHING = "STOP_FETCHING";
export const ADD_SKILL = "ADD_SKILL";
export const ADD_TEAMLEAD = "ADD_TEAMLEAD";
export const GET_TEAMLEADS = "GET_TEAMLEADS";
export const COLLAPSE_AGENT_VIEW = "COLLAPSE_AGENT_VIEW";
export const COLLAPSE_BOTTOMBOX_DRIVER_VIEW = "COLLAPSE_BOTTOMBOX_DRIVER_VIEW";
export const COLLAPSE_SURVEY_VIEW = "COLLAPSE_SURVEY_VIEW";
export const COLLAPSE_DASHBOARD_VIEW = "COLLAPSE_DASHBOARD_VIEW";

export const ADD_TEAM = "ADD_TEAM";
export const GET_RCAS = "GET_RCAS";
export const GET_RCA = "GET_RCA";
export const REMOVE_RCA = "REMOVE_RCA";
export const GET_BOTTOMBOX = "GET_BOTTOMBOX";
export const UPDATE_SURVEY = "UPDATE_SURVEY";
export const UPDATE_RCA = "UPDATE_RCA";
export const DELETE_RCA = "DELETE_RCA";

export const GET_ERRORS = "GET_ERRORS";

export const UPDATE_BOTTOMBOX_DRIVER_STATE = "UPDATE_BOTTOMBOX_DRIVER_STATE";
export const UPDATE_AGENTS_COMPONENT_STATE = "UPDATE_AGENTS_COMPONENT_STATE";
export const UPDATE_CHART_DATA = "UPDATE_CHART_DATA";
export const UPDATE_AGENT_CHART_DATA = "UPDATE_AGENT_CHART_DATA";
export const UPDATE_SELECTED_MONTH = "UPDATE_SELECTED_MONTH";
export const UPDATE_SELECTED_WEEK = "UPDATE_SELECTED_WEEK";
export const UPDATE_SELECTED_YEAR = "UPDATE_SELECTED_YEAR";

// Bottombox Drivers
export const GET_DSAT_CODE1 = "GET_DSAT_CODE1";
export const DELETE_DSAT_CODE1 = "DELETE_DSAT_CODE1";
export const UPDATE_DSAT_CODE1 = "UPDATE_DSAT_CODE1";
export const GET_BB_DRIVER_CODE2 = "GET_BB_DRIVER_CODE2";
export const UPDATE_BB_DRIVER_CODE2 = "UPDATE_BB_DRIVER_CODE2";
export const UPDATE_BB_DRIVER_CODE3 = "UPDATE_BB_DRIVER_CODE3";
export const DELETE_BB_DRIVER_CODE2 = "DELETE_BB_DRIVER_CODE2";
export const DELETE_BB_DRIVER_CODE3 = "DELETE_BB_DRIVER_CODE3";
export const GET_BB_DRIVER_CODE3 = "GET_BB_DRIVER_CODE3";
export const ADD_DSAT_CODE1 = "ADD_DSAT_CODE1";
export const ADD_BB_DRIVER_CODE2 = "ADD_BB_DRIVER_CODE2";
export const ADD_BB_DRIVER_CODE3 = "ADD_BB_DRIVER_CODE3";

// Authentication
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

// messages

export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const GET_MESSAGES = "GET_MESSAGES";

export const GET_ALL_DATA = "GET_ALL_DATA";

// Agent requests

export const UPDATE_AGENT = "UPDATE_AGENT";
export const ADD_AGENT = "ADD_AGENT";

// CCMS

export const SET_TABLE_PAGE = "SET_TABLE_PAGE";
export const GET_MAILS = "GET_MAILS";
export const GET_CCMS = "GET_CCMS";
export const ACK_ENTRY = "ACK_ENTRY";
export const ADD_UPDATE = "ADD_UPDATE";
export const GET_COMMENTS = "GET_COMMENTS";
export const GET_BUSINESS_UNIT = "GET_BUSINESS_UNIT";
export const GET_TICKET_STATUS = "GET_TICKET_STATUS";
export const GET_ESCALATION_TYPE = "GET_ESCALATION_TYPE";
export const GET_SITE_CODE = "GET_SITE_CODE";
export const GET_ACCOUNTABLE_TEAM = "GET_ACCOUNTABLE_TEAM";
export const GET_CCMS_OWNER = "GET_CCMS_OWNER";
export const GET_TICKET_TYPE = "GET_TICKET_TYPE";
export const GET_SILO = "GET_SILO";
export const UPDATE_CCMS = "UPDATE_CCMS";
export const COMPLETE_CCMS = "COMPLETE_CCMS";
export const GET_CCMS_STATUS = "GET_CCMS_STATUS";
export const ADD_COMMENT = "ADD_COMMENT";
export const GET_SELECTED_CCMS = "GET_SELECTED_CCMS";
export const GET_SELECTED_CCMS_ONLY = "GET_SELECTED_CCMS_ONLY";
export const REMOVE_SELECTED_CCMS = "REMOVE_SELECTED_CCMS";
export const GET_CCMS_LIST_PER_USER = "GET_CCMS_LIST_PER_USER";
export const CLOSE_COLLAPSE = "CLOSE_COLLAPSE";
export const OPEN_COLLAPSE = "OPEN_COLLAPSE";
export const SEARCH = "SEARCH";
export const GET_CCMS_ADMIN_LIST = "GET_CCMS_ADMIN_LIST";
export const GET_USERS_LIST = "GET_USERS_LIST";
export const REMOVE_USER_FROM_CCMS_ADMIN = "REMOVE_USER_FROM_CCMS_ADMIN";
export const ADD_USER_TO_CCMS_ADMIN = "ADD_USER_TO_CCMS_ADMIN";
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const FETCHING_COMMENTS = "FETCHING_COMMENTS";
export const ADD_REQUEST_ACCESS = "ADD_REQUEST_ACCESS";
export const GET_REQUEST_ACCESS = "GET_REQUEST_ACCESS";
export const DENY_REQUEST_ACCESS = "DENY_REQUEST_ACCESS";
export const ADD_CCMS_OWNER = "ADD_CCMS_OWNER";
export const REMOVE_ACCESS_REQUEST = "REMOVE_ACCESS_REQUEST";

// DRIVERS
export const GET_CAUSE_CODE = "GET_CAUSE_CODE";
export const ADD_CAUSE_CODE = "ADD_CAUSE_CODE";
export const DELETE_CAUSE_CODE = "DELETE_CAUSE_CODE";
export const EDIT_CAUSE_CODE = "EDIT_CAUSE_CODE";

export const GET_ESCALATION_DRIVER = "GET_ESCALATION_DRIVER";
export const ADD_ESCALATION_DRIVER = "ADD_ESCALATION_DRIVER";
export const DELETE_ESCALATION_DRIVER = "DELETE_ESCALATION_DRIVER";
export const EDIT_ESCALATION_DRIVER = "EDIT_ESCALATION_DRIVER";

export const GET_ESCALATION_DRIVER_CAUSE = "GET_ESCALATION_DRIVER_CAUSE";
export const ADD_ESCALATION_DRIVER_CAUSE = "ADD_ESCALATION_DRIVER_CAUSE";
export const DELETE_ESCALATION_DRIVER_CAUSE = "DELETE_ESCALATION_DRIVER_CAUSE";
export const EDIT_ESCALATION_DRIVER_CAUSE = "EDIT_ESCALATION_DRIVER_CAUSE";

// CCMS RCA
export const CLOSE_RCA_MODAL = "CLOSE_RCA_MODAL";
export const GET_CCMS_RCA = "GET_CCMS_RCA";
export const COMPLETE_CCMS_RCA = "COMPLETE_CCMS_RCA";
export const TOGGLE_ACTIVE_TAB = "TOGGLE_ACTIVE_TAB";

export const COMPLETE_FNI = "COMPLETE_FNI";
export const GET_FNI_LIST = "GET_FNI_LIST";

export const SUBMIT_CA = "SUBMIT_CA";
export const GET_CA_LIST = "GET_CA_LIST";

// GENERAL DATA CRUD

export const ADD_BUSINESS_UNIT = "ADD_BUSINESS_UNIT";
export const DELETE_BUSINESS_UNIT = "DELETE_BUSINESS_UNIT";
export const EDIT_BUSINESS_UNIT = "EDIT_BUSINESS_UNIT";

export const ADD_TICKET_TYPE = "ADD_TICKET_TYPE";
export const DELETE_TICKET_TYPE = "DELETE_TICKET_TYPE";
export const EDIT_TICKET_TYPE = "EDIT_TICKET_TYPE";

export const ADD_SILO = "ADD_SILO";
export const DELETE_SILO = "DELETE_SILO";
export const EDIT_SILO = "EDIT_SILO";

export const ADD_CCMS_STATUS = "ADD_CCMS_STATUS";
export const DELETE_CCMS_STATUS = "DELETE_CCMS_STATUS";
export const EDIT_CCMS_STATUS = "EDIT_CCMS_STATUS";

export const ADD_SITE_CODE = "ADD_SITE_CODE";
export const DELETE_SITE_CODE = "DELETE_SITE_CODE";
export const EDIT_SITE_CODE = "EDIT_SITE_CODE";

export const ADD_ACCOUNTABLE_TEAM = "ADD_ACCOUNTABLE_TEAM";
export const DELETE_ACCOUNTABLE_TEAM = "DELETE_ACCOUNTABLE_TEAM";
export const EDIT_ACCOUNTABLE_TEAM = "EDIT_ACCOUNTABLE_TEAM";

export const ADD_ESCALATION_TYPE = "ADD_ESCALATION_TYPE";
export const DELETE_ESCALATION_TYPE = "DELETE_ESCALATION_TYPE";
export const EDIT_ESCALATION_TYPE = "EDIT_ESCALATION_TYPE";
