export const CHECK_BUTTON_COLOR = "CHECK_BUTTON_COLOR";

export const GET_SURVEYS = "GET_SURVEYS";
export const ADD_SURVEY = "ADD_SURVEY";
export const DELETE_SURVEY = "DELETE_SURVEY";
export const MODAL_TOGGLE = "MODAL_TOGGLE";
export const GET_SURVEY = "GET_SURVEY";
export const REMOVE_SURVEY = "REMOVE_SURVEY";
export const GET_AGENT = "GET_AGENT";
export const GET_AGENTS = "GET_AGENTS";
export const GET_SKILLS = "GET_SKILLS";
export const ADD_FAILED_SURVEY = "ADD_FAILED_SURVEY";

export const GET_BOTTOMBOX_SURVEY_VIEW = "GET_BOTTOMBOX_SURVEY_VIEW";
export const GET_TOPBOX_SURVEY_VIEW = "GET_TOPBOX_SURVEY_VIEW";
export const GET_COMPLETED_SURVEY_VIEW = "GET_COMPLETED_SURVEY_VIEW";
export const GET_ALL_SURVEY_VIEW = "GET_ALL_SURVEY_VIEW";

export const GET_TEAMS = "GET_TEAMS";
export const ADD_RCA = "ADD_RCA";
export const UPDATE_BOTTOMBOX_NOT_COMPLETED = "UPDATE_BOTTOMBOX_NOT_COMPLETED";
export const FETCHING = "FETCHING";
export const STOP_FETCHING = "STOP_FETCHING";
export const ADD_SKILL = "ADD_SKILL";
export const ADD_TEAMLEAD = "ADD_TEAMLEAD";
export const GET_TEAMLEADS = "GET_TEAMLEADS";
export const COLLAPSE_AGENT_VIEW = "COLLAPSE_AGENT_VIEW";
export const COLLAPSE_BOTTOMBOX_DRIVER_VIEW = "COLLAPSE_BOTTOMBOX_DRIVER_VIEW";
export const COLLAPSE_SURVEY_VIEW = "COLLAPSE_SURVEY_VIEW";
export const COLLAPSE_DASHBOARD_VIEW = "COLLAPSE_DASHBOARD_VIEW";

export const ADD_TEAM = "ADD_TEAM";
export const GET_RCAS = "GET_RCAS";
export const GET_RCA = "GET_RCA";
export const REMOVE_RCA = "REMOVE_RCA";
export const GET_BOTTOMBOX = "GET_BOTTOMBOX";
export const UPDATE_SURVEY = "UPDATE_SURVEY";
export const UPDATE_RCA = "UPDATE_RCA";
export const DELETE_RCA = "DELETE_RCA";

export const GET_ERRORS = "GET_ERRORS";

export const UPDATE_BOTTOMBOX_DRIVER_STATE = "UPDATE_BOTTOMBOX_DRIVER_STATE";
export const UPDATE_AGENTS_COMPONENT_STATE = "UPDATE_AGENTS_COMPONENT_STATE";
export const UPDATE_CHART_DATA = "UPDATE_CHART_DATA";
export const UPDATE_AGENT_CHART_DATA = "UPDATE_AGENT_CHART_DATA";
export const UPDATE_SELECTED_MONTH = "UPDATE_SELECTED_MONTH";
export const UPDATE_SELECTED_WEEK = "UPDATE_SELECTED_WEEK";
export const UPDATE_SELECTED_YEAR = "UPDATE_SELECTED_YEAR";

// Bottombox Drivers
export const GET_DSAT_CODE1 = "GET_DSAT_CODE1";
export const DELETE_DSAT_CODE1 = "DELETE_DSAT_CODE1";
export const UPDATE_DSAT_CODE1 = "UPDATE_DSAT_CODE1";
export const GET_BB_DRIVER_CODE2 = "GET_BB_DRIVER_CODE2";
export const UPDATE_BB_DRIVER_CODE2 = "UPDATE_BB_DRIVER_CODE2";
export const UPDATE_BB_DRIVER_CODE3 = "UPDATE_BB_DRIVER_CODE3";
export const DELETE_BB_DRIVER_CODE2 = "DELETE_BB_DRIVER_CODE2";
export const DELETE_BB_DRIVER_CODE3 = "DELETE_BB_DRIVER_CODE3";
export const GET_BB_DRIVER_CODE3 = "GET_BB_DRIVER_CODE3";
export const ADD_DSAT_CODE1 = "ADD_DSAT_CODE1";
export const ADD_BB_DRIVER_CODE2 = "ADD_BB_DRIVER_CODE2";
export const ADD_BB_DRIVER_CODE3 = "ADD_BB_DRIVER_CODE3";

// Authentication
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

// messages

export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const GET_MESSAGES = "GET_MESSAGES";

export const GET_ALL_DATA = "GET_ALL_DATA";

// Agent requests

export const UPDATE_AGENT = "UPDATE_AGENT";
export const ADD_AGENT = "ADD_AGENT";

// CCMS

export const GET_MAILS = "GET_MAILS";
export const ACK_ENTRY = "ACK_ENTRY";
export const ADD_UPDATE = "ADD_UPDATE";
export const GET_COMMENTS = "GET_COMMENTS";
