# Generated by Django 3.0.3 on 2020-03-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('reference_number', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('callback_reference_number', models.CharField(blank=True, max_length=100)),
                ('related_incident_record', models.CharField(blank=True, max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('site_location', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('user_location', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('vip', models.CharField(blank=True, max_length=100)),
                ('customer_email_address', models.EmailField(blank=True, max_length=254)),
                ('date_time', models.CharField(blank=True, max_length=100)),
                ('origination_source', models.CharField(blank=True, max_length=100)),
                ('call_type', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=100)),
                ('service_type', models.CharField(blank=True, max_length=100)),
                ('service', models.CharField(blank=True, max_length=100)),
                ('service_component', models.CharField(blank=True, max_length=100)),
                ('assignment_group', models.CharField(blank=True, max_length=100)),
                ('q1', models.CharField(blank=True, max_length=10000)),
                ('q2', models.CharField(blank=True, max_length=10000)),
                ('q2a', models.CharField(blank=True, max_length=10000)),
                ('q3', models.CharField(blank=True, max_length=500)),
                ('q3a', models.CharField(blank=True, max_length=10000)),
                ('q4', models.CharField(blank=True, max_length=10000)),
                ('q5', models.CharField(blank=True, max_length=10000)),
                ('q6', models.CharField(blank=True, max_length=10000)),
                ('average_score', models.CharField(blank=True, max_length=100)),
                ('fulfillment', models.CharField(blank=True, max_length=100)),
                ('follow_up_comments', models.CharField(blank=True, max_length=10000)),
                ('originating_ticket_description', models.CharField(blank=True, max_length=500)),
                ('budi_bu', models.CharField(blank=True, max_length=100)),
                ('budi_lv7', models.CharField(blank=True, max_length=100)),
                ('bu_catg', models.CharField(blank=True, max_length=100)),
                ('date_issued', models.CharField(blank=True, max_length=100)),
                ('bottombox', models.IntegerField(blank=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=100)),
                ('date_uploaded', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
