# Generated by Django 3.0.3 on 2020-03-09 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_agent_team'),
        ('csat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountableTeam',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='BB_Driver_Code2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BB_Driver_Code3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bb_Driver_Code2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bb_Driver_Code3s', to='csat.BB_Driver_Code2')),
            ],
        ),
        migrations.CreateModel(
            name='DSAT_Code1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RCA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_silo_issue_based', models.CharField(blank=True, max_length=100)),
                ('service', models.CharField(blank=True, max_length=100)),
                ('service_component', models.CharField(blank=True, max_length=100)),
                ('brief_description', models.CharField(blank=True, max_length=3000)),
                ('user_verbatim', models.CharField(blank=True, max_length=3000)),
                ('actual_issue', models.CharField(blank=True, max_length=3000)),
                ('controllability', models.CharField(choices=[('ITSD Controllable', 'ITSD Controllable'), ('Non ITSD Controllable', 'Non ITSD Controllable')], default='ITSD Controllable', max_length=100)),
                ('related_ticket_number', models.CharField(blank=True, max_length=100)),
                ('q1_answer', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20)),
                ('contacted_customer', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20)),
                ('summary', models.CharField(blank=True, max_length=3000)),
                ('obs_in_call', models.CharField(blank=True, max_length=3000)),
                ('accountable_entity', models.CharField(blank=True, max_length=1000)),
                ('overall_reason_dsat', models.CharField(blank=True, max_length=3000)),
                ('coaching', models.BooleanField(default=False)),
                ('corrective_actions', models.CharField(blank=True, max_length=3000)),
                ('completed_by', models.CharField(blank=True, max_length=100)),
                ('date_completed', models.CharField(blank=True, max_length=100)),
                ('accountable_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='csat.AccountableTeam')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='agents.Agent')),
                ('bb_driver_code2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bb_driver_codes_2', to='csat.BB_Driver_Code2')),
                ('bb_driver_code3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bb_driver_codes_3', to='csat.BB_Driver_Code3')),
                ('dsat_code1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dsat_code1', to='csat.DSAT_Code1')),
                ('surveyed_ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='surveyed_tickets', to='csat.Survey')),
            ],
        ),
        migrations.AddField(
            model_name='bb_driver_code2',
            name='dsat_Code1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bb_Driver_Code2s', to='csat.DSAT_Code1'),
        ),
    ]
