# Generated by Django 3.0.3 on 2020-03-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csat', '0003_auto_20200311_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='rca',
            name='employee_type',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='rca',
            name='service_bb_ticket',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='rca',
            name='service_component_bb_ticket',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='rca',
            name='transferred_bb',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
