# Generated by Django 3.0.3 on 2020-03-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csat', '0004_auto_20200326_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='scope',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
