# Generated by Django 3.0.3 on 2020-03-26 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_auto_20200322_0145'),
        ('csat', '0005_survey_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rca',
            name='support_silo_issue_based',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_skills', to='agents.AgentSkill'),
        ),
    ]
