# Generated by Django 3.0.3 on 2020-04-09 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csat', '0006_auto_20200327_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsatAccessRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csat_access_request_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
