# Generated by Django 3.0.3 on 2020-03-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('operator_lan_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Operator Lan ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('wave', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
