# Generated by Django 2.2.4 on 2019-08-31 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeamLead',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='Owner Name')),
                ('operator_lan_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Operator Lan ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('wave', models.CharField(blank=True, max_length=100, null=True)),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.Skill')),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.TeamLead')),
            ],
        ),
    ]
