# Generated by Django 3.0.3 on 2020-03-09 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents', '0003_agentskill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='name',
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
