# Generated by Django 3.0.3 on 2020-03-10 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_agent_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
        migrations.AddField(
            model_name='team',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_agents', to='agents.Agent'),
        ),
    ]
