# Generated by Django 3.0.3 on 2020-03-11 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_auto_20200310_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_agents', to='agents.Agent'),
        ),
    ]
