# Generated by Django 3.0.3 on 2020-03-11 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_auto_20200311_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='agent',
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_member_agents', to='agents.Agent')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_member_teams', to='agents.Team')),
            ],
        ),
    ]
