# Generated by Django 3.0.3 on 2020-03-21 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_auto_20200311_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='agent_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_agent_skills', to='agents.AgentSkill'),
        ),
    ]
