# Generated by Django 3.0.3 on 2020-04-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_auto_20200322_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_lead',
        ),
        migrations.AddField(
            model_name='team',
            name='team_leads',
            field=models.ManyToManyField(to='agents.TeamLead'),
        ),
    ]
