# Generated by Django 3.0.3 on 2020-04-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_auto_20200403_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='teams',
            field=models.ManyToManyField(to='agents.Team'),
        ),
    ]
