app_id: f133db8c-bc4d-4f7a-bc12-e25860e5cffb
app_secret: "miTa8-P1TZoCis.gPT].U4vUvfbOEj1f"
redirect: http://localhost:8000/callback
scopes: openid profile offline_access user.read calendars.read mail.read mail.send user.readbasic.all mail.read.shared mail.readwrite
authority: https://login.microsoftonline.com/common
authorize_endpoint: /oauth2/v2.0/authorize
token_endpoint: /oauth2/v2.0/token
