app_id: f133db8c-bc4d-4f7a-bc12-e25860e5cffb
app_secret: "miTa8-P1TZoCis.gPT].U4vUvfbOEj1f"
# redirect: http://localhost:8000/callback
# redirect: https://localhost/callback
redirect: https://10.235.83.26/callback
scopes: openid profile offline_access user.read user.readbasic.all calendars.read mail.read mail.send mail.read.shared mail.readwrite mail.readwrite.shared mail.send.shared
authority: https://login.microsoftonline.com/common
authorize_endpoint: /oauth2/v2.0/authorize
token_endpoint: /oauth2/v2.0/token
