# Generated by Django 3.0.2 on 2020-01-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('expires_in', models.IntegerField()),
                ('ext_expires_in', models.IntegerField()),
                ('access_token', models.CharField(max_length=10000)),
                ('refresh_token', models.CharField(max_length=10000)),
                ('id_token', models.CharField(max_length=10000)),
                ('expires_at', models.FloatField()),
            ],
        ),
    ]
