# Generated by Django 3.0.2 on 2020-01-27 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.TextField()),
                ('contributor_name', models.CharField(max_length=2000)),
                ('comment_entry_date', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_id', models.CharField(editable=False, max_length=5000)),
                ('email_subject', models.CharField(blank=True, max_length=2000)),
                ('email_body', models.TextField(blank=True)),
                ('sender_name', models.CharField(blank=True, max_length=2000)),
                ('sender_email_address', models.CharField(blank=True, max_length=2000)),
                ('acknowledged_by', models.CharField(max_length=2000)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(blank=True, default=False)),
                ('date_acknowledged', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Mailbox_Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_on', models.BooleanField(default=False)),
                ('mailbox_name', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Credentials',
        ),
        migrations.AddField(
            model_name='comment',
            name='mail',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mails', to='ccms.Mail'),
        ),
    ]
