# Generated by Django 3.0.2 on 2020-01-28 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ccms', '0002_auto_20200127_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountableTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='CCMSStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='EscalationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Silo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='SiteCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='acknowledged_by',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='date_acknowledged',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='is_acknowledged',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='is_resolved',
        ),
        migrations.CreateModel(
            name='CCMSOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ccms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_by', models.CharField(max_length=2000)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(blank=True, default=False)),
                ('date_acknowledged', models.CharField(max_length=2000)),
                ('accountable_team', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountable_teams', to='ccms.AccountableTeam')),
                ('business_unit', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_units', to='ccms.BusinessUnit')),
                ('ccms_owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ccms_owners', to='ccms.CCMSOwner')),
                ('ccms_status', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ccms_status', to='ccms.CCMSStatus')),
                ('escalation_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalation_types', to='ccms.EscalationType')),
                ('mail', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mails', to='ccms.Mail')),
                ('silo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='silos', to='ccms.Silo')),
                ('site_code', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_codes', to='ccms.SiteCode')),
                ('ticket_status', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_status', to='ccms.TicketStatus')),
                ('ticket_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='ccms.TicketType')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='ccms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ccms', to='ccms.Ccms'),
        ),
    ]
