# Generated by Django 3.0.2 on 2020-01-30 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccms', '0003_auto_20200128_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccms',
            name='escalated_by',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='ccms',
            name='escalated_email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='ccms',
            name='escalated_name',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='ccms',
            name='escalated_ticket',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='ccms',
            name='lan_id',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='ccms',
            name='specific_business_unit',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='ccms',
            name='accountable_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountable_teams', to='ccms.AccountableTeam'),
        ),
        migrations.AlterField(
            model_name='ccms',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_units', to='ccms.BusinessUnit'),
        ),
        migrations.AlterField(
            model_name='ccms',
            name='ccms_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ccms_owners', to='ccms.CCMSOwner'),
        ),
        migrations.AlterField(
            model_name='ccms',
            name='ccms_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ccms_status', to='ccms.CCMSStatus'),
        ),
        migrations.AlterField(
            model_name='ccms',
            name='escalation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalation_types', to='ccms.EscalationType'),
        ),
        migrations.AlterField(
            model_name='ccms',
            name='silo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='silos', to='ccms.Silo'),
        ),
        migrations.AlterField(
            model_name='ccms',
            name='site_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_codes', to='ccms.SiteCode'),
        ),
        migrations.AlterField(
            model_name='ccms',
            name='ticket_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_status', to='ccms.TicketStatus'),
        ),
        migrations.AlterField(
            model_name='ccms',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='ccms.TicketType'),
        ),
        migrations.AlterField(
            model_name='escalationtype',
            name='name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
