# Generated by Django 3.0.2 on 2020-01-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccms', '0004_auto_20200130_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='receivedDateTime',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='ccms',
            name='acknowledged_by',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='ccms',
            name='date_acknowledged',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
