# Generated by Django 3.0.2 on 2020-02-01 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ccms', '0005_auto_20200130_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccms',
            name='rca_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ccms',
            name='summary_complaint',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
