# Generated by Django 3.0.2 on 2020-02-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccms', '0006_auto_20200201_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccms',
            name='is_complaint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ccms',
            name='is_compliment',
            field=models.BooleanField(default=False),
        ),
    ]
