# Generated by Django 3.0.2 on 2020-02-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccms', '0007_auto_20200201_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ccms',
            name='is_compliment',
        ),
        migrations.AlterField(
            model_name='ccms',
            name='summary_complaint',
            field=models.TextField(blank=True),
        ),
    ]
