# Generated by Django 3.0.2 on 2020-02-05 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ccms', '0008_auto_20200204_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='contributor_name',
        ),
        migrations.AddField(
            model_name='comment',
            name='contibutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contibutors', to=settings.AUTH_USER_MODEL),
        ),
    ]
