# Generated by Django 3.0.2 on 2020-02-05 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ccms', '0009_auto_20200205_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='contibutor',
        ),
        migrations.AddField(
            model_name='comment',
            name='contributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to=settings.AUTH_USER_MODEL),
        ),
    ]
