# Generated by Django 3.0.2 on 2020-02-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccms', '0010_auto_20200205_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_entry_date',
            field=models.DateField(auto_now=True),
        ),
    ]
