# Generated by Django 3.0.2 on 2020-02-06 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cba_auth', '0002_auto_20200126_1714'),
        ('ccms', '0011_auto_20200206_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='cba_auth.Auth_Details'),
        ),
    ]
