# Generated by Django 3.0.3 on 2020-02-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccms', '0012_auto_20200206_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ccms_status_during_comment',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
