# Generated by Django 3.0.3 on 2020-02-16 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cba_auth', '0002_auto_20200126_1714'),
        ('ccms', '0013_comment_ccms_status_during_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CcmsRca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_on', models.DateField(auto_now=True)),
                ('ccms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ccms_rca', to='ccms.Ccms')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_by_rca', to='cba_auth.Auth_Details')),
            ],
        ),
        migrations.CreateModel(
            name='CcmsAccessRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='cba_auth.Auth_Details')),
            ],
        ),
    ]
