# Generated by Django 3.0.3 on 2020-02-16 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cba_auth', '0002_auto_20200126_1714'),
        ('ccms', '0014_ccmsaccessrequest_ccmsrca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccmsaccessrequest',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='cba_auth.Auth_Details'),
        ),
    ]
