# Generated by Django 3.0.3 on 2020-02-17 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccms', '0015_auto_20200216_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='CauseCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EscalationDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2000, null=True)),
                ('cause_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cause_codes', to='ccms.CauseCode')),
            ],
        ),
        migrations.AddField(
            model_name='ccmsrca',
            name='agent_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='ccmsrca',
            name='agent_silo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_silos', to='ccms.Silo'),
        ),
        migrations.AddField(
            model_name='ccmsrca',
            name='ccms_ticket_description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='ccmsrca',
            name='controllability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_silos', to='ccms.AccountableTeam'),
        ),
        migrations.AddField(
            model_name='ccmsrca',
            name='ticket_description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.CreateModel(
            name='EscalationDriverCause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2000, null=True)),
                ('escalation_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_drivers', to='ccms.EscalationDriver')),
            ],
        ),
    ]
