# Generated by Django 3.0.3 on 2020-02-17 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccms', '0016_auto_20200217_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccmsrca',
            name='business_unit',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='ccmsrca',
            name='cause_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rca_cause_codes', to='ccms.CauseCode'),
        ),
        migrations.AddField(
            model_name='ccmsrca',
            name='escalation_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rca_escalation_drivers', to='ccms.EscalationDriver'),
        ),
        migrations.AddField(
            model_name='ccmsrca',
            name='escalation_driver_cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rca_escalation_driver_causes', to='ccms.EscalationDriverCause'),
        ),
        migrations.AddField(
            model_name='ccmsrca',
            name='specific_bu',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='ccmsrca',
            name='team_spg_accountability',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
