# Generated by Django 3.0.3 on 2020-02-17 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccms', '0017_auto_20200217_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccms',
            name='ccms_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ccms_status', to='ccms.CCMSStatus'),
        ),
    ]
