# Generated by Django 3.0.3 on 2020-02-19 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cba_auth', '0002_auto_20200126_1714'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ccms', '0020_auto_20200218_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccms',
            name='accountable_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountable_teams', to='ccms.AccountableTeam'),
        ),
        migrations.AlterField(
            model_name='ccms',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_units', to='ccms.BusinessUnit'),
        ),
        migrations.AlterField(
            model_name='ccms',
            name='escalation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_types', to='ccms.EscalationType'),
        ),
        migrations.AlterField(
            model_name='ccms',
            name='silo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='silos', to='ccms.Silo'),
        ),
        migrations.AlterField(
            model_name='ccms',
            name='site_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_codes', to='ccms.SiteCode'),
        ),
        migrations.AlterField(
            model_name='ccms',
            name='ticket_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_status', to='ccms.TicketStatus'),
        ),
        migrations.AlterField(
            model_name='ccms',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_types', to='ccms.TicketType'),
        ),
        migrations.AlterField(
            model_name='ccmsowner',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ccmsrca',
            name='agent_silo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_silos', to='ccms.Silo'),
        ),
        migrations.AlterField(
            model_name='ccmsrca',
            name='cause_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rca_cause_codes', to='ccms.CauseCode'),
        ),
        migrations.AlterField(
            model_name='ccmsrca',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_by_rca', to='cba_auth.Auth_Details'),
        ),
        migrations.AlterField(
            model_name='ccmsrca',
            name='controllability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_silos', to='ccms.AccountableTeam'),
        ),
        migrations.AlterField(
            model_name='ccmsrca',
            name='escalation_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rca_escalation_drivers', to='ccms.EscalationDriver'),
        ),
        migrations.AlterField(
            model_name='ccmsrca',
            name='escalation_driver_cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rca_escalation_driver_causes', to='ccms.EscalationDriverCause'),
        ),
    ]
