# Generated by Django 3.0.3 on 2020-02-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccms', '0021_auto_20200220_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccmsrca',
            name='completed_on',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
