# Generated by Django 3.0.3 on 2020-02-21 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccms', '0022_auto_20200220_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccmsrca',
            name='event_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ccmsrca',
            name='controllability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controllabilities', to='ccms.AccountableTeam'),
        ),
    ]
