# Generated by Django 3.0.3 on 2020-02-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccms', '0023_auto_20200221_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccmsrca',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
