# Generated by Django 3.0.3 on 2020-02-21 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccms', '0024_ccmsrca_ticket_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingsAndInvestigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('ticket_number', models.CharField(blank=True, max_length=2000, null=True)),
                ('description', models.TextField(blank=True)),
                ('ccms_rca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings_and_investigation_ccms_rcas', to='ccms.CcmsRca')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, max_length=2000, null=True)),
                ('description', models.TextField(blank=True)),
                ('ccms_rca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrective_action_ccms_rcas', to='ccms.CcmsRca')),
            ],
        ),
    ]
