# Generated by Django 3.0.3 on 2020-02-22 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccms', '0026_findingsandinvestigation_submitted_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RcaTicketNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, max_length=2000, null=True, unique=True)),
                ('event_description', models.TextField(blank=True)),
                ('submitted_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='findingsandinvestigation',
            name='ccms_rca',
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='submitted_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='findingsandinvestigation',
            name='ticket_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_numbers', to='ccms.RcaTicketNumber'),
        ),
    ]
