# Generated by Django 3.0.3 on 2020-02-22 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccms', '0027_auto_20200222_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ccmsrca',
            name='event_description',
        ),
        migrations.RemoveField(
            model_name='ccmsrca',
            name='ticket_number',
        ),
        migrations.RemoveField(
            model_name='correctiveaction',
            name='ccms_rca',
        ),
        migrations.AddField(
            model_name='rcaticketnumber',
            name='ccms_rca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ccms_rca_ticket_numbers', to='ccms.CcmsRca'),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='ticket_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ca_ticket_numbers', to='ccms.RcaTicketNumber'),
        ),
        migrations.AlterField(
            model_name='findingsandinvestigation',
            name='ticket_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fni_ticket_numbers', to='ccms.RcaTicketNumber'),
        ),
    ]
