# Generated by Django 3.0.3 on 2020-02-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccms', '0029_auto_20200222_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctiveaction',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='findingsandinvestigation',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
