# Generated by Django 3.0.3 on 2020-02-24 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccms', '0030_auto_20200222_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correctiveaction',
            name='ccms_rca',
        ),
        migrations.RemoveField(
            model_name='correctiveaction',
            name='ticket_number',
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='fni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ca_fni', to='ccms.FindingsAndInvestigation'),
        ),
    ]
