# Generated by Django 3.0.3 on 2020-03-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccms', '0033_auto_20200225_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
