# Generated by Django 3.0.3 on 2020-03-31 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccms', '0034_recipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipient',
            old_name='email',
            new_name='name',
        ),
    ]
